version:     "0000--11-Sep-2022"
copyright:   "2022"
author:      "ferryhusnil"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/ferryhusnil/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]